name: Verify Issue
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  check_run:

jobs:
  verify-issue:
    uses: regulaforensics/reusable-workflows/.github/workflows/verify-linked-issue.yaml@main
